require "bundler/gem_tasks"
require "rake/extensiontask"
require 'rake/testtask'

BASE_TEST_FILE_LIST = Dir['test/**/test_*.rb']

task :build => :compile

Rake::ExtensionTask.new("arg_scanner") do |ext|
  ext.lib_dir = "lib/arg_scanner"
end

desc "Test debase."
Rake::TestTask.new(:test) do |t|
  t.libs += ['./ext', './lib']
  t.test_files = FileList[BASE_TEST_FILE_LIST]
  t.verbose = true
end

task :test => :lib

task :default => [:clobber, :compile, :spec]
